caracteres = input('Digite algo \n')
print('Você digitou: {}'.format(caracteres))
print(caracteres, 'o tipo primitivo desse valor é: ', type(caracteres))
print(caracteres, 'pode ser convertido para inteiro ou float?', caracteres.isnumeric())
print(caracteres, 'é uma letra ou várias letras apenas?', caracteres.isalpha())
print(caracteres, 'é um número decimal?', caracteres.isdecimal())
print(caracteres, 'é alfanumérico?', caracteres.isalnum())
print(caracteres, 'é um caractere ascii?', caracteres.isascii())
print(caracteres, 'é um digito?', caracteres.isdigit())
print(caracteres, 'pode ser usado como nome de variável?', caracteres.isidentifier())
print(caracteres, 'é escrito somente com letras minúsculas e outros caracteres?', caracteres.islower())
print(caracteres, 'é escrito somente com letras maiúsculas e outros caracteres?', caracteres.isupper())
print(caracteres, 'É UMA string CAPTALIZADA (Formato de título)?', caracteres.istitle())
print(caracteres, 'é composto apenas por espaços?', caracteres.isspace())
print(caracteres, 'pode ser impresso no console?', caracteres.isprintable())

